/* tslint:disable */
// This file is generated from the API. Do not edit this file.

import { request } from "./request";

interface ApiPromise<T> extends PromiseLike<T> {
    onError(errorCode: "ValidationError", cb: (data: { fields : { [k: string]: string[] }, messages : string[] }) => void);
    onError(errorCode: "NotFound", cb: (data: null) => void);
    onError(errorCode: "NotAuthorized", cb: (data: null) => void);
    onError(errorCode: "Forbidden", cb: (data: null) => void);
    onError(errorCode: "UndefinedError", cb: (data: null) => void);
}
export const Api = {
    Account : {
        Register : (body: { email : string, password : string }): ApiPromise<string> =>
            request("Account/Register", "POST", body),
        LoggedIn : (): ApiPromise<{ id : string, email : string }> =>
            request("Account/LoggedIn", "POST", false),
        ChangePassword : (body: { currentPassword : string, newPassword : string }): ApiPromise<string> =>
            request("Account/ChangePassword", "POST", body),
        ResetPassword : (body: { email : string, code : string, newPassword : string }): ApiPromise<string> =>
            request("Account/ResetPassword", "POST", body),
        ForgotPassword : (body: { email : string }): ApiPromise<string> =>
            request("Account/ForgotPassword", "POST", body),
        ConfirmEmail : (body: { email : string, code : string }): ApiPromise<string> =>
            request("Account/ConfirmEmail", "POST", body),
        LogoutAllApplications : (): ApiPromise<string> =>
            request("Account/LogoutAllApplications", "POST", false)
    },
    OpenId : {
        Logout : (): ApiPromise<void> =>
            request("OpenId/Logout", "GET", false),
        Authorize : (): ApiPromise<void> =>
            request("OpenId/Authorize", "POST", false),
        Accept : (): ApiPromise<void> =>
            request("OpenId/Authorize/Accept", "POST", false),
        Deny : (): ApiPromise<void> =>
            request("OpenId/Authorize/Deny", "POST", false)
    },
    Frontend : {
        Thingies : {
            GetByName : (body: { name : string }): ApiPromise<{ id : number, name : string }> =>
                request("Frontend/Thingies/GetByName", "POST", body),
            GetById : (body: { id : number }): ApiPromise<{ id : number, name : string }> =>
                request("Frontend/Thingies/GetById", "POST", body),
            Store : (body: { thingie : { id : number, name : string } }): ApiPromise<{ id : number, name : string }> =>
                request("Frontend/Thingies/Store", "POST", body)
        }
    }
};
